version: '3.1'
services:  
  venus:
    image: space-scanner-alien:latest
    restart: always
    ports:
      - 9090:9090
    environment:
      SERVER_PORT: 9090
      APP_PLANET: venus
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATA_MONGODB_HOST: mongo

  mars:
    image: space-scanner-alien:latest
    restart: always
    ports:
      - 9091:9091
    environment:
      SERVER_PORT: 9091
      APP_PLANET: mars
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATA_MONGODB_HOST: mongo
    
  gateway:
    image: space-scanner-gateway:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      APP_SERVICE_VENUS: "http://venus:9090"
      APP_SERVICE_MARS: "http://mars:9091"

  mongo:
    image: mongo
    restart: always
    ports:
      - 2701:2701
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongodb:
  mongodb_config: